### ISSUE TITLE
how to use the physical Ethernet Port instead of loopback port?

### ISSUE THREAD

**Issue by lcysys** [GENIVI/vsomeip#194]
I am new to the linux , now i build the example try to manually publish the service into the network, however when i run the executable , i want to use the physical ethernet port , it automatically use the loopback port , i can't change , i have configured the IP address in the configuration file, is there anything i missed ? 
![image](https://user-images.githubusercontent.com/61775369/102296850-2d6b2c80-3f89-11eb-82d6-b0992aa3db50.png)
![image](https://user-images.githubusercontent.com/61775369/102297471-4fb17a00-3f8a-11eb-91af-b824f9e4fe50.png)
![image](https://user-images.githubusercontent.com/61775369/102297517-6061f000-3f8a-11eb-98b6-eadcbdc8b25a.png)

**Comment by lutzbichler** [comment]
It looks as if the configuration file is not (correctly) read, because the configuration file defines a routing manager and the log from the application claims that this is not the case. However, the "unicast" configuration variable is the only thing that is needed to be defined in order to select the ethernet device.

**Comment by lcysys** [comment]
Thank you for the explanation, got it , :) ,now this should be closed!
