### ISSUE TITLE
[Consultation] Which IDE in Ubuntu should I use to manage the vsomeip source code?

### ISSUE THREAD

**Issue by npucloud** [GENIVI/vsomeip#45]
Dear all,

I am using Ubuntu 16.04，and I want to put the vsomeip source code in an IDE so it would be easy to trace the call to a function or the reference to a variable. 
I tried Eclipse and built a Makefile project with existing code but the project cannot be built,showing:
make all 
make: *** No rule to make target 'all'.  Stop.
I guess it's a problem with the project configuration but don't know how to fix it.
**So I wonder is there any recommanded IDE for this vsomeip project?**
I want to manage both the source code of vsomeip itself and its application demos.

Thanks a lot. ^_^

**Comment by gunnarx** [comment]
@npucloud vSomeIP is a **cmake** based project.  That is clearly written in the README, which also shows that it is necessary (like in all cmake projects) to run cmake before make as part of the build steps.

I believe vsomeip to be a very standard cmake project without any special tricks, so there should be no unique support needed here.  This is not the place to ask for generic IDE support or advice.

You should study how to use the IDE you chose (for example, search for help on setting up a **cmake** project in **Eclipse**).   If it is not already built in, then IDEs will normally allow you to edit the build steps, so you could write the steps that are documented in README.

I will, on behalf of the maintainer, close this issue because it is not related to the component.
