### ISSUE TITLE
Event calls

### ISSUE THREAD

**Issue by krishnaruby** [GENIVI/vsomeip#70]
Im trying to publish an event message to it's subscribers. I'm not very clear whether it's blocking call or non blocking call ?Is there any design document to understand vsomeip implementation ?

**Comment by DevNaga** [comment]
Any publish can be handled according to the purpose of the publication of data - 

1. you can publish periodically in a timer
2. publish when some particular event occur

subscription on the otherhand, becomes always an event

1. you register a callback
2. callback will be called once the publisher sends out anything on the wire.

I refer to generally CommonAPI that abstracts the vsomeip and provide an RPC like interface. Usually the subscription callbacks get called in a thread that is created by the underlying CommonAPI layer so that means the data reception become asynchronous (and thus care must be taken when you are queing this data somewhere and some other thread accessing this)


Look at CommonAPI for more details regarding this: https://github.com/GENIVI/capicxx-someip-tools/wiki/CommonAPI-C---SomeIP-in-10-minutes
